name: meteora
channels:
  - conda-forge
dependencies:
  - gdal=3.9.2
  - myst-parser=4.0.0
  - nbsphinx=0.9.5
  - pandoc=3.5
  - pip=24.2
  - pip:
      - sphinxemoji==0.3.1
  - pydata-sphinx-theme=0.15.4
  - python=3.12
  - sphinx=8.0.2
