name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          create-args: >-
            gdal>=3.3
            pip
            python=${{ matrix.python-version }}
            tox
            tox-gh
            ${{ matrix.python-version == '3.13' && 'ipython' || '' }}
            ${{ matrix.python-version == '3.13' && 'pandoc' || '' }}

      - name: get API keys from secrets
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: ".keys.env"
          fileDir: "."
          encodedString: ${{ secrets.API_KEYS }}

      - name: test with tox
        run: tox
        env:
          CONDA_EXE: mamba
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: list files
        run: ls -l .
